language: php
sudo: false
dist: trusty
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
os:
    - windows
    - linux
install:
    - travis_retry composer install --no-interaction
script:
    - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
